[build]
  command = "npx expo export --platform web --output-dir dist/web"
  publish = "dist/web"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_VERSION = "22"
